# Generated by Django 3.1.14 on 2022-09-24 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
    ]
