# Generated by Django 3.1.14 on 2022-09-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220925_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image1',
            field=models.ImageField(default='default.png', upload_to='post/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(default='default.png', upload_to='post/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image3',
            field=models.ImageField(default='default.png', upload_to='post/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image4',
            field=models.ImageField(default='default.png', upload_to='post/'),
        ),
    ]
