# Generated by Django 3.1.14 on 2022-09-26 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220926_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photodigm',
            fields=[
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='posts.post')),
                ('photodigm', models.ImageField(default='default.png', upload_to='post/photodigm/')),
            ],
        ),
    ]
